# config-version:3.0
# The configuration file has changed since version 1.1.4. Please carefully check and modify before use!

# Define a scheduled task. The key name can be any, but must be unique.
broadcast:
  # Define the interval time for the interval task, in seconds.
  interval: 10
  time: -1 # This indicates that this task is an interval task.
  # Define the command for the scheduled task. It can be any valid console command.
  commands:
    # It should be "commands" not "command"!
    - "say Hello, this is Taskscheduler!"
    - "say Which is created by CerealAxis."
  # To set multiple commands, follow the format and continue writing below. Pay attention to the formatting!

# Example 2
#clear:
#  interval: 30
#  commands:
#    - "say clear the server"
# For a single command, set it up like this.

# Define a scheduled task. The key name can be any, but must be unique.
clearing:
  # Define the interval time for the interval task, in seconds.
  interval: -1 #-1 means disabled
  time: 12:00 # This indicates that this task is a scheduled task.
  # The time and interval parameters cannot be enabled at the same time, otherwise an error will occur.
  # Define the command for the scheduled task. It can be any valid console command.
  commands:
    # It should be "commands" not "command"!
    - "say Hello, this is Taskscheduler!"
    - "say Which is created by CerealAxis."
  # To set multiple commands, follow the format and continue writing below. Pay attention to the formatting!