name: taskscheduler
version: '${project.version}'
main: xaviermc.top.taskscheduler.taskscheduler
api-version: '1.20'

commands:
  taskscheduler:
    description: 重载插件
    usage: /taskscheduler reload

