name: taskscheduler
version: '${project.version}'
main: xaviermc.top.taskscheduler.taskscheduler
api-version: '1.20'
author: CerealAxis

commands:
  taskscheduler:
    description: reload the taskscheduler
    usage: /taskscheduler reload
    aliases: ts

